name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost
      DB_USER: root
      DB_NAME: mydatabase

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.2'

    - name: Use GitHub Secrets
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        echo "Password is set"
        go build -v ./...