version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: .
    environment:
      - DATABASE_URL=${DB_URL}
    env_file:
      - .env
    depends_on:
      - db
    ports: 
      - "8080:8080"
    networks:
    - app-network

networks:
  app-network:
    driver: bridge