// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	NotificationID     int32
	RecurringPaymentID pgtype.Int4
	NotificationDate   pgtype.Timestamp
	NotificationStatus pgtype.Text
}

type RecurringPayment struct {
	RecurringPaymentID int32
	PayerID            pgtype.UUID
	ReceiverID         pgtype.UUID
	PayerName          string
	ReceiverName       string
	Amount             pgtype.Numeric
	NotificationType   pgtype.Text
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	DayOfMonth         pgtype.Int2
	PaymentStatus      pgtype.Text
}

type User struct {
	UserID       pgtype.UUID
	Name         string
	SecondName   string
	Email        string
	Password     string
	UserDocument string
	PhoneNumber  pgtype.Text
	BornDate     pgtype.Date
	CreatedAt    pgtype.Timestamp
}
